### ISSUE TITLE
大佬是否有剩余焊接好的ob瑞萨板子

### ISSUE THREAD

**Issue by RCSN** [zhangjinke/J-Link-OB-RA4M2#1]
rt
大佬有剩余的板子吗，出售也行，主要是想验证下riscv的平台能否调试

**Comment by zhangjinke** [comment]
目前只焊接了一套，没有多余的，使用J-Link Commander测试可以正常连接、调试玄铁E902内核的单片机

**Comment by RCSN** [comment]
好的，谢谢大佬回复

**Comment by rayc345** [comment]
楼上都是大佬，为了做hpm的调试器找到了这里。感谢各位的付出！
