### ISSUE TITLE
关于vcom

### ISSUE THREAD

**Issue by lizimu2020** [zhangjinke/J-Link-OB-RA4M2#2]
我的硬件是ra4m2adcfp（512KB 100PIN），jlink驱动识别正常，jtag和swd使用正常。但vcom串口在win的设备管理器里没有显示，是需要在哪里配置么？

**Comment by zhangjinke** [comment]
VCOM需要使用J-Link Configurator使能后才能使用，具体可以查看https://wiki.segger.com/Using_J-Link_VCOM_functionality

**Comment by lizimu2020** [comment]
开启成功，谢谢。

**Comment by zhangjinke** [comment]
不客气
