### ISSUE TITLE
other parts compatible?

### ISSUE THREAD

**Issue by danyhm** [zhangjinke/J-Link-OB-RA4M2#3]
the document at
[segger](https://www.segger.com/downloads/jlink/UM08040_JLinkOBRA4M2.pdf)
says it should be compatible with 
R7FA4M2AC3CNE
but it's not tested.
have you tested if it works with that part?
it's cheaper than [R7FA4M2AB3CFL] or [R7FA4M2AB3CNE]

**Comment by tsl0922** [comment]
It should be compatible, I'm using R7FA4M2AD3CFL#AA0, it works fine.

**Comment by zhangjinke** [comment]
I haven't tested it, but I know from the datasheet that the only difference between them is FLASH size and package, so it should work.
